const express = require('express');
const router = express.Router();
const aiService = require('../services/aiService');

// VERIFY WEBHOOK
router.get('/webhook', (req, res) => {
  const VERIFY_TOKEN = process.env.META_VERIFY_TOKEN || 'hotelbase_secret_token_123';
  
  let mode = req.query['hub.mode'];
  let token = req.query['hub.verify_token'];
  let challenge = req.query['hub.challenge'];

  if (mode && token) {
    if (mode === 'subscribe' && token === VERIFY_TOKEN) {
      console.log('WEBHOOK_VERIFIED');
      res.status(200).send(challenge);
    } else {
      res.sendStatus(403);
    }
  } else {
    res.sendStatus(400);
  }
});

function isAutomatedGreeting(text) {
  if (!text) return false;
  const lower = text.toLowerCase();
  return (
    lower.includes('filiallardan birini tanlang') ||
    lower.includes('family hotelga xush kelibsiz') ||
    (lower.includes('buxoro filiali') && lower.includes('samarqand filiali')) ||
    lower.includes('avtomatik javob') ||
    lower.includes('instant reply')
  );
}

// RECEIVE MESSAGES
router.post('/webhook', async (req, res) => {
  const body = req.body;
  console.log('WEBHOOK PAYLOAD:', JSON.stringify(body, null, 2));

  // Instagram or Page JSON object
  if (body.object === 'instagram' || body.object === 'page') {
    res.status(200).send('EVENT_RECEIVED'); // Send 200 early to prevent retries

    if (!body.entry) return;

    for (const entry of body.entry) {
      if (!entry.messaging) continue;

      for (const webhook_event of entry.messaging) {
        const senderId = webhook_event.sender.id;
        
        // Handle echo messages (when a human operator, bot or Meta ad auto-reply sends a message)
        if (webhook_event.message && webhook_event.message.is_echo) {
          const recipientId = webhook_event.recipient?.id;
          const operatorText = webhook_event.message.text;

          // Check if this echo was generated by our own bot API
          if (aiService.isSentByBot(recipientId, operatorText)) {
            console.log(`[BOT ECHO] Message echo for bot to ${recipientId} ignored.`);
            continue;
          }

          // Check if this echo is an automated greeting / instant reply from Meta Ads
          if (isAutomatedGreeting(operatorText)) {
            console.log(`[AUTOMATED GREETING ECHO] Meta Ads greeting detected for ${recipientId}. Not pausing AI.`);
            aiService.recordIncomingGreeting(recipientId, operatorText);
            continue;
          }

          // If echo is from a real human operator (Instagram app or Meta Business Suite)
          if (recipientId && operatorText) {
            console.log(`[OPERATOR TAKEOVER] Operator replied to ${recipientId}: "${operatorText}". AI paused for 15 minutes.`);
            aiService.handleOperatorTakeover(recipientId, operatorText, 15);
          }
          continue;
        }

        if (!webhook_event.message?.is_echo) {
          let messageToSend = webhook_event.message?.text || 
                              webhook_event.postback?.title || 
                              webhook_event.postback?.payload || 
                              webhook_event.message?.quick_reply?.payload;

          // If no direct text, check if user sent a location pin or map attachment
          if (!messageToSend && webhook_event.message?.attachments?.length > 0) {
            console.log(`[ATTACHMENT DETECTED] From ${senderId}, extracting coordinates...`);
            const coords = await aiService.extractLocationCoordinates(
              webhook_event.message.mid,
              webhook_event.message.attachments
            );

            if (coords) {
              const nearest = aiService.findNearestBranches(coords.lat, coords.lng, 3);
              console.log(`[LOCATION FOUND] Lat: ${coords.lat}, Lng: ${coords.lng}. Nearest: ${nearest[0].name} (${nearest[0].distanceKm} km)`);
              messageToSend = `[Mijoz o'zining jonli GPS lokatsiyasini yubordi (Koordinatalari: ${coords.lat.toFixed(4)}, ${coords.lng.toFixed(4)}). Ushbu manzilga eng yaqin filiallarimiz: 1. ${nearest[0].title} - ${nearest[0].subtitle} (${nearest[0].distanceKm} km), 2. ${nearest[1].title} - ${nearest[1].subtitle} (${nearest[1].distanceKm} km), 3. ${nearest[2].title} - ${nearest[2].subtitle} (${nearest[2].distanceKm} km)]`;
            }
          }

          if (messageToSend) {
            console.log(`Processing message for ${senderId}: ${messageToSend}`);
            try {
              // Send to AI Service
              await aiService.handleInstagramMessage(senderId, messageToSend, req.app.get('io'));
            } catch (error) {
              console.error('Error handling Instagram message via AI:', error);
            }
          }
        }
      }
    }
  } else {
    res.sendStatus(404);
  }
});

module.exports = router;
